name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
jobs:
  main:
    name: Nx Cloud - Main Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Install Nx Cloud
        run: yarn add nx-cloud
      - name: Start CI Run
        run: yarn nx-cloud start-ci-run --stop-agents-after="build" --agent-count=3
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - uses: actions/checkout@v2
      - run: yarn build --prod
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_REACT_TOOLBOX_785C5 }}'
          channelId: live
          projectId: react-toolbox-785c5
