name: react-toolbox-app

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    name: Nx Cloud - Main Job
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.11.3
    with:
      number-of-agents: 3
      init-commands: |
        yarn nx-cloud start-ci-run --stop-agents-after="build" --agent-count=3
      parallel-commands: |
        yarn nx-cloud record -- yarn nx format:check
      parallel-commands-on-agents: |
        yarn nx affected --target=lint --parallel=3
        yarn nx affected --target=test --parallel=3 --ci --code-coverage
        yarn nx affected --target=build --parallel=3
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: nx build react-toolbox

      - name: Deploy to Nx Cloud
        uses: nrwl/nx-cloud-github-action@v1
        with:
          workspaceSlug: react-toolbox
          token: ${{ secrets.NX_CLOUD_TOKEN }}
  agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.11.3
    with:
      number-of-agents: 3
